//material-ui
import { createStyles, makeStyles, Theme } from '@material-ui/core/styles'
//style
export const useStyles = makeStyles((theme: Theme) =>
  createStyles({
    link1: {
      boxSizing: 'border-box',
      margin: '0px',
      minWidth: '0px',
      textDecoration: 'underline',
      color: '#c99400',
      fontSize: '14px',
      fontWeight: 600,
      cursor: 'pointer',
      '&:hover': {
        color: '#c99400',
      },
    },
    link2: {
      boxSizing: 'border-box',
      margin: '0px',
      minWidth: '0px',
      textDecoration: 'underline',
      color: '#c99400',
      fontSize: '14px',
      fontWeight: 400,
      cursor: 'pointer',
      display: 'none',
      '&:hover': {
        color: '#f0b90b',
      },
      [theme.breakpoints.up(767)]: {
        display: 'block',
      },
    },
    feeRoot: {
      paddingTop: '32px',
      paddingBottom: '16px',
    },
    feeContent: {
      marginBottom: '48px',
    },
    contentPart1: {
      boxSizing: 'border-box',
      margin: '0px',
      minWidth: '0px',
      fontWeight: 500,
      fontSize: '16px',
      lineHeight: '24px',
      color: 'rgb(30, 35, 41)',
    },
    contentPart2: {
      marginTop: '8px',
      display: 'flex',
      flexDirection: 'row',
      alignItems: 'center',
      flexWrap: 'wrap',
    },
    contentPart21: {
      boxSizing: 'border-box',
      margin: '0px',
      minWidth: '40px',
      fontWeight: 400,
      fontSize: '14px',
      lineHeight: '20px',
      color: 'rgb(112, 122, 138)',
    },
    contentPart22: {
      boxSizing: 'border-box',
      margin: '0px 8px',
      minWidth: '40px',
      fontWeight: 500,
      fontSize: '20px',
      lineHeight: '28px',
      color: '#000000',
    },
    contentPart23: {
      boxSizing: 'border-box',
      margin: '4px 0px 0px',
      minWidth: '0px',
      // fontWeight: 500,
      fontSize: '14px',
      color: 'rgb(112, 122, 138)',
      textDecorationLine: 'line-through',
    },
    part3Root: {
      display: 'flex',
      flexDirection: 'row',
      marginTop: '8px',
      alignItems: 'center',
    },
    contentPart3: {
      boxSizing: 'border-box',
      minWidth: '0px',
      fontWeight: 400,
      fontSize: '14px',
      lineHeight: '20px',
      color: 'rgb(112, 122, 138)',
    },
    part3Chip: {
      boxSizing: 'border-box',
      margin: '0px 0px 0px 4px',
      minWidth: '0px',
      fontWeight: 400,
      fontSize: '12px',
      lineHeight: '16px',
      paddingLeft: '4px',
      paddingRight: '4px',
      display: 'flex',
      backgroundColor: 'rgb(245, 245, 245)',
      color: 'rgb(112, 122, 138)',
    },
    part3Icon: {
      display: 'flex',
      fontSize: '16px',
      marginLeft: '4px',
    },
    arrow: {
      color: theme.palette.common.black,
    },
    tooltip: {
      backgroundColor: theme.palette.common.black,
    },
    last_root: {
      boxSizing: 'border-box',
      margin: '0px',
      minWidth: '0px',
      textDecoration: 'none',
      color: 'rgb(201, 148, 0)',
      fontSize: '24px',
      '&:hover': {
        textDecoration: 'underline',
        color: 'rgb(240, 185, 11)',
      },
    },
    contentLast: {
      boxSizing: 'border-box',
      margin: '0px',
      minWidth: '0px',
      backgroundColor: 'rgb(250, 250, 250)',
      boxShadow: 'rgb(20 21 26 / 4%) 0px 1px 2px, rgb(71 77 87 / 4%) 0px 3px 6px, rgb(20 21 26 / 10%) 0px 0px 1px',
      borderRadius: '4px',
      padding: '16px',
      position: 'relative',
      zIndex: 0,
    },
    lastBackground: {
      boxSizing: 'border-box',
      minWidth: '0px',
      position: 'absolute',
      top: '0px',
      left: '0px',
      right: '0px',
      bottom: '0px',
      zIndex: 1,
      margin: '0px',
      // background: 'url(/src/assets/image/bottomBackground.jpg) 0% 0% / cover',
      background: '#000000',
      borderRadius: '4px',
    },
    lastContent: {
      boxSizing: 'border-box',
      margin: '0px',
      minWidth: '0px',
      position: 'relative',
      zIndex: 2,
    },
    contentImportant: {
      boxSizing: 'border-box',
      minWidth: '0px',
      margin: '0px 0px 0px 8px',
      fontSize: '14px',
      color: 'rgb(255, 255, 255)',
    },
    transferLink: {
      marginLeft: '8px',
      color: '#f0b90b',
      textDecoration: 'underline',
      cursor: 'pointer',
      '&:hover': {
        color: '#f0b90b',
      },
    },
    transferTooltip: {
      color: '#ffffff',
      backgroundColor: '#5e6673',
      borderRadius: '4px',
      padding: '8px 12px',
      maxWidth: '270px',
      '& p': {
        fontWeight: 400,
        fontSize: '12px',
        lineHeight: '16px',
      },
    },
    transferTooltipArrow: {
      color: '#5e6673',
    },
  }),
)
